
POST http://localhost:5000/order/new
Content-Type: application/json

{
    "userId": "611ec41d3a06813e10332344",
    "products": [
        "611ec41d3a06813e10332349",
        "611ec41d3a06813e1033234c"
    ],
    "shippingAddress": {
        "address": "Park Street",
        "city": "Kolkata",
        "postalCode": "713331",
        "country": "India"
    }
}



#######  GET all orders
GET http://localhost:5000/order/


####### UPDATE particular order to paid
PUT http://localhost:5000/order/update/paid/6122829e51d62627d89a44ca




####### UPDATE order to delivered
PUT http://localhost:5000/order/update/delivered/6122829e51d62627d89a44ca
