# POST http://localhost:5000/user/register
# Content-Type: application/json

# {
#     "name": "Shubham",
#     "email": "shubham@gmail.com",
#     "password": "user1234"
# }


POST http://localhost:5000/user/login
Content-Type: application/json

{    
    "email": "shubham@gmail.com",
    "password": "user1234"
}

